server.port=80

spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://127.0.0.1:3306/campscore
spring.datasource.hikari.username=memorizeTODO
spring.datasource.hikari.password=jsw77889900

mybatis.configuration.map-underscore-to-camel-case=true

logging.level.root=INFO
logging.level.org.mybatis=DEBUG
logging.level.org.springframework=DEBUG

